update another.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,12 +35,18 @@ jobs:
           java-version: "17"
           distribution: "oracle"
 
+      - name: Install SuiteCloud CLI globally
+        run: npm install -g @oracle/suitecloud-cli --acceptsuitecloudsdklicense
+
+      - name: Check SuiteCloud CLI
+        run: suitecloud --version || echo "SuiteCloud CLI not found"
+
       # Step 4: Install dependencies in 'test-project'
       - name: Install dependencies in test-project
-        run: npm install --acceptsuitecloudsdklicense
+        run: npm install
         working-directory: ./test-project
 
       # Step 5: Authenticate project against NetSuite
       - name: Authenticate project
-        run: npx suitecloud account:setup:ci --authid ${{ vars.NS_AUTH_ID }} --certificateid ${{ secrets.NS_CERTIFICATE_ID }} --privatekeypath ../private.key --account ${{ vars.NS_ACCOUNT_ID }}
+        run: suitecloud account:setup:ci --authid ${{ vars.NS_AUTH_ID }} --certificateid ${{ secrets.NS_CERTIFICATE_ID }} --privatekeypath ../private.key --account ${{ vars.NS_ACCOUNT_ID }}
         working-directory: ./test-project
